services:
  mysql:
    image: mysql:8.0
    container_name: appointment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appointment_db
      MYSQL_USER: roosti_db
      MYSQL_PASSWORD: secure_roosti_pass_2026
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
